parameters:
  name: 'ESLint'
  vmImage: 'ubuntu-16.04'
  node_version: 10.x
  install_scope: 'eslint'
  job_script: 'npx eslint .'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.node_version }}
    displayName: 'Install Node.js'
  - ${{ if eq(parameters.install_scope, 'eslint') }}:
    - script: npm i --no-save eslint eslint-config-futagozaryuu
  - ${{ if eq(parameters.install_scope, 'npm') }}:
    - script: npm install
  - ${{ if eq(parameters.install_scope, 'yarn') }}:
    - script: yarn install --ignore-engines
  - script: ${{ parameters.job_script }}
