parameters:
  name: 'Lint'
  vmImage: 'ubuntu-16.04'
  node_version: 10.x
  install_scope: 'eslint'
  job_script: 'npx eslint .'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.node_version }}
    displayName: 'Install Node.js'
  - ${{ if eq(parameters.install_scope, 'eslint') }}:
    - script: npm i --no-save eslint eslint-config-futagozaryuu
      displayName: 'Installing minimal dependencies'
  - ${{ if eq(parameters.install_scope, 'npm') }}:
    - script: npm install
      displayName: 'Installing dependencies from NPM'
  - ${{ if eq(parameters.install_scope, 'yarn') }}:
    - script: yarn install --ignore-engines
      displayName: 'Installing dependencies using Yarn'
  - script: ${{ parameters.job_script }}
    displayName: 'Run ESLint'
