parameters:
  id: 'NodeTestRunner'
  name: 'Test'
  vmImage: 'ubuntu-16.04'
  vmOS: 'Linux'
  node_version: 10.x
  package_manager: 'yarn'
  before: []
  success_script: False
  fail_script: False
  after: []
  publish_test_results_to_pipelines: False
  publish_code_coverage_to_pipelines: False

jobs:
- job: ${{ parameters.id }}
  displayName: ${{ format('{0} ({1}, Node {2})', parameters.name, parameters.vmOS, parameters.node_version) }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.node_version }}
    displayName: 'Install Node.js'
  - ${{ if eq(parameters.package_manager, 'npm') }}:
    - script: npm install
      displayName: 'Instal dependencies from NPM'
  - ${{ if eq(parameters.package_manager, 'yarn') }}:
    - script: yarn install --ignore-engines
      displayName: 'Instal dependencies using Yarn'
  - ${{ parameters.before }}
  - script: npm test
    displayName: 'Run tests'
  - script: ${{ parameters.success_script }}
    displayName: 'Running post-test success script'
    condition: and(succeeded(), ne(variables['parameters.success_script'], False))
  - script: ${{ parameters.fail_script }}
    displayName: 'Running post-test fail script'
    condition: and(failed(), ne(variables['parameters.fail_script'], False))
  - ${{ parameters.after }}
  - ${{ if eq(parameters.publish_test_results_to_pipelines, True) }}:
    - task: PublishTestResults@2
      displayName: 'Publish test results (Azure Pipelines)'
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: 'coverage/junit.xml'
  - ${{ if eq(parameters.publish_code_coverage_to_pipelines, True) }}:
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results (Azure Pipelines)'
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
