parameters:
  id: 'NodeTestRunner'
  name: 'Test'
  vmImage: 'ubuntu-16.04'
  vmOS: 'Linux'
  node_version: 10.x
  package_manager: 'yarn'
  before: []
  npm_test: True
  after: []
  publish_test_results_to_pipelines: False
  publish_code_coverage_to_pipelines: False

jobs:
- template: node.yml
  parameters:
    id: ${{ parameters.id }}
    name: ${{ format('{0} ({1}, Node {2})', parameters.name, parameters.vmOS, parameters.node_version) }}
    vmImage: ${{ platform.vmImage }}
    node_version: ${{ node_version.node_version }}
    npm_installer: ${{ parameters.package_manager }}
    actions:
      - ${{ parameters.before }}
      - ${{ if eq(parameters.npm_test, True) }}:
        - script: npm test
          displayName: 'Run tests'
      - ${{ parameters.after }}
      - ${{ if eq(parameters.publish_test_results_to_pipelines, True) }}:
        - task: PublishTestResults@2
          displayName: 'Publish test results (Azure Pipelines)'
          condition: succeededOrFailed()
          inputs:
            testRunner: JUnit
            testResultsFiles: 'coverage/junit.xml'
      - ${{ if eq(parameters.publish_code_coverage_to_pipelines, True) }}:
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish code coverage results (Azure Pipelines)'
          inputs: 
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
