parameters:
  name: 'Test'
  platforms:
    Linux: 'ubuntu-16.04'
  node_versions:
    v6: 6.x
    v8: 8.x
    v10: 10.x
  package_manager: 'yarn'
  before: []
  after: []
  azure_coverage: False

jobs:
- ${{ each platform in parameters.platforms }}:
  - ${{ each node_version in parameters.node_versions }}:
    - template: node-test-runner.yml
      parameters:
        id: ${{ format('{0}_Node_{1}', platform.key, node_version.key) }}
        name: ${{ parameters.name }}
        vmImage: ${{ platform.value }}
        vmOS: ${{ platform.key }}
        node_version: ${{ node_version.value }}
        package_manager: ${{ parameters.package_manager }}
        before: ${{ parameters.before }}
        after: ${{ parameters.after }}
        azure_coverage: ${{ parameters.azure_coverage }}
