parameters:
  name: 'Test'
  vmImage: 'ubuntu-16.04'
  node_versions:
    v6: 6.x
    v8: 8.x
    v10: 10.x
  install_tool: 'yarn'
  before: []
  after: []
  azure_coverage: False

jobs:
- ${{ each node_version in parameters.node_versions }}:
  - ${{ each pair in node_version }}:
    - template: node-test.yml
      parameters:
        id: ${{ format('NodeTestRunner_{0}', pair.key) }}
        name: ${{ parameters.name }}
        vmImage: ${{ parameters.vmImage }}
        node_version: ${{ pair.value }}
        install_tool: ${{ parameters.install_tool }}
        before: ${{ parameters.before }}
        after: ${{ parameters.after }}
        azure_coverage: ${{ parameters.azure_coverage }}
